### ISSUE TITLE
Fail when use organization secret in workflow

### ISSUE THREAD

**Issue by tuoping** [wearerequired/git-mirror-action#14]
Automatic mirror works when I use a secret stored in the source repo. But failed when I used a secret stored in organization.
Here is my workflow .yml file:
```yml
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_REPO_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:source.git"
          destination-repo: "git@gitee.com:destination.git"
```
